apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rc23-redis-cluster
  labels:
    app.kubernetes.io/name: rc23-redis-cluster
    app.kubernetes.io/instance: rc23-redis-cluster
spec:
  replicas: 6
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app.kubernetes.io/name: rc23-redis-cluster
      app.kubernetes.io/instance: rc23-redis-cluster
  serviceName: cluster-srv-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rc23-redis-cluster
        app.kubernetes.io/instance: rc23-redis-cluster
    spec:
      containers:
        - name: redis-cluster
          image: redis-cluster:3
          imagePullPolicy: "IfNotPresent"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rc23-redis-cluster-secret
                  key: redis-password
            - name: REDIS_CLUSTER_ANNOUNCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: REDIS_CLUSTER_ANNOUNCE_PORT
              value: "6379"
            - name: REDIS_NODES
              value: "rc23-redis-cluster-0.cluster-srv-headless rc23-redis-cluster-1.cluster-srv-headless rc23-redis-cluster-2.cluster-srv-headless rc23-redis-cluster-3.cluster-srv-headless rc23-redis-cluster-4.cluster-srv-headless rc23-redis-cluster-5.cluster-srv-headless "
            - name: REDIS_CLUSTER_ANNOUNCE_BUS_PORT
              value: "16379"
            - name: REDIS_CLUSTER_REPLICAS
              value: "1"
            - name: REDIS_CLUSTER_DNS
              value: "cluster-srv"
            - name: REDIS_CLUSTER_DNS_TTL
              value: "30"
            - name: REDIS_CLUSTER_DNS_REFRESH
              value: "10"
            - name: REDIS_CLUSTER_DNS_RETRIES
              value: "5"
            - name: REDIS_CLUSTER_DNS_TIMEOUT
              value: "2"
            - name: REDIS_CLUSTER_DNS_NOT_FOUND_TTL
              value: "15"
            - name: REDIS_CLUSTER_DNS_UPDATE_INTERVAL
              value: "60"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 250m
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              # Backwards compatibility change
              if ! [[ -f /opt/pacloud/redis/etc/redis.conf ]]; then
                  echo COPYING FILE
                  cp  /opt/pacloud/redis/etc/redis-default.conf /opt/pacloud/redis/etc/redis.conf
              fi
              pod_index=($(echo "$POD_NAME" | tr "-" "\n"))
              pod_index="${pod_index[-1]}"
              if [[ "$pod_index" == "0" ]]; then
                export REDIS_CLUSTER_CREATOR="yes"
                export REDIS_CLUSTER_REPLICAS="1"
              fi
              /opt/pacloud/scripts/redis-cluster/entrypoint.sh /opt/pacloud/scripts/redis-cluster/run.sh
          ports:
          - name: tcp-redis
            containerPort: 6379
          volumeMounts:
          # - mountPath: /opt/pacloud/redis/etc/redis.conf
            # name: redis-tmp-conf
          - mountPath: /pacloud/redis/data
            name: redis-data

  volumeClaimTemplates:
  - metadata:
      name: redis-data
      labels:
        app.kubernetes.io/instance: rc23-redis-cluster
        app.kubernetes.io/name: rc23-redis-cluster
    spec:
      resources:
        requests:
          storage: 8Gi
      accessModes:
      - ReadWriteOnce

        
          
    