apiVersion: v1
kind: Service
metadata:
  name: cluster-srv
  labels:
    app.kubernetes.io/name: rc23-redis-cluster
    app.kubernetes.io/instance: rc23-redis-cluster
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: redis
    - name: redis-cluster
      port: 16379
      targetPort: redis-cluster
  selector:
    app.kubernetes.io/name: rc23-redis-cluster
    app.kubernetes.io/instance: rc23-redis-cluster

---
apiVersion: v1
kind: Service
metadata:
  name: cluster-srv-headless
  labels:
    app.kubernetes.io/name: rc23-redis-cluster
    app.kubernetes.io/instance: rc23-redis-cluster
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: redis
    - name: redis-cluster
      port: 16379
      targetPort: redis-cluster
  selector:
    app.kubernetes.io/name: rc23-redis-cluster
    app.kubernetes.io/instance: rc23-redis-cluster