image:
  #repository: redis-cluster
  repository: dongdongqiang/redis-cluster
  tag: 4.6
  pullPolicy: IfNotPresent
  imagePullSecrets: defaultdocker
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""
  redis:
    password: ""
cluster:
  nodes: 10
  init: "true"
  replicas: 1
  update:
    addNodes: "false"
    currentNumberOfNodes: 16
    currentNumberOfReplicas: 1
  externalAccess:
    enabled: false

usePassword: true

diagnosticMode:
  enabled: false
  command: "redis-cli --cluster check"
  args: "global"
tls:
  enabled: false
updateJob:
  ## @param updateJob.activeDeadlineSeconds Number of seconds the Job to create the cluster will be waiting for the Nodes to be ready.
  ##
  activeDeadlineSeconds: 600
podSecurityContext:
  enabled: false

containerSecurityContext: 
  enabled: false

serviceAccount:
  create: false
  name: redis-cluster