apiVersion: v1
kind: Secret
metadata:
  # name: rc23-redis-cluster-secret
  name: {{ .Release.Name }}-redis-cluster-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-redis-cluster
type: Opaque
data:
  redis-password: "cGFzc3dvcmQ="